---
# k8s control-plane group variables (ansible05)
# kubeadm control-plane ports + Calico VXLAN + node_exporter

firewall_ports: "{{ kubeadm_control_plane_ports + k8s_calico_ports + ['9100/tcp'] }}"
