---
galaxy_info:
  role_name: harbor_containers
  author: alaureijs
  description: Sync container images to Harbor and check upstream versions
  license: GPL-3.0-or-later
  min_ansible_version: "2.17"
  platforms:
    - name: EL
      versions:
        - "10"
  galaxy_tags:
    - harbor
    - containers
    - sync
    - images

dependencies: []
