---
portal_web_root: /var/www

nginx_directories:
  - path: "{{ nginx_web_root }}/ca-portal"
  - path: "{{ nginx_web_root }}/acme"
  - path: "{{ nginx_web_root }}/ca"
  - path: "{{ nginx_web_root }}/documents"
  - path: "{{ nginx_web_root }}/documents/sync-reports"
    owner: "{{ nginx_content_owner }}"
    group: "{{ nginx_content_group }}"
    mode: "0755"

nginx_vhosts:
  - name: portal
    server_name: pki.homelab.internal
    web_root: "{{ nginx_web_root }}/ca-portal"
    ssl_cert: /etc/pki/tls/certs/portal.crt
    ssl_key: /etc/pki/tls/private/portal.key
    conf: /etc/nginx/conf.d/portal.conf
    template: vhost.conf.j2
    acme_challenge: true
    ca_alias: true
    acme_proxy: true
    landing_page: index.html.j2

  - name: documents
    server_name: documents.homelab.internal
    web_root: "{{ nginx_web_root }}/documents"
    ssl_cert: /etc/pki/tls/certs/documents.crt
    ssl_key: /etc/pki/tls/private/documents.key
    conf: /etc/nginx/conf.d/documents.conf
    template: vhost.conf.j2
    autoindex: true
    landing_page: false

certificates_extra:
  - name: portal
    type: stepca
    extra_sans:
      - "DNS:pki.homelab.internal"
  - name: documents
    type: stepca
    extra_sans:
      - "DNS:documents.homelab.internal"
