---
# Connection
ansible_host: 192.168.100.11

# VM host-specific
vm_name: ansible02
vm_mac: "52:54:00:aa:00:11"
vm_ip: 192.168.100.11

# VM specs (overrides group defaults)
vm_vcpus: 2
vm_memory: 4096
vm_disk: 80

vm_hostname: ansible02

# Hardening — Podman requires IP forwarding
hardening_ip_forwarding: true

# OpenTelemetry filelog paths
otel_log_paths:
  - /var/log/nginx/*.log
