---
all:
  children:
    pki:
      hosts:
        ansible04:
    portal:
      hosts:
        ansible04:
    k8s:
      children:
        k8s_cp:
        k8s_workers:
    k8s_cp:
      hosts:
        ansible05:
    k8s_workers:
      hosts:
        ansible06:
        ansible07:
        ansible08:
    libvirt:
      hosts:
        ansible04:
        ansible05:
        ansible06:
        ansible07:
        ansible08:
