---
all:
  children:
    harbor:
      hosts:
        ansible01:
    monitoring:
      hosts:
        ansible02:
    elk:
      hosts:
        ansible03:
    libvirt:
      hosts:
        ansible01:
        ansible02:
        ansible03:
