---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    common_install_packages:
      - curl
    common_remove_packages: []
    common_enable_chrony: false
    common_logrotate_configs: []

  roles:
    - role: common
