auth:
  existingSecret: gitlab-minio

mode: standalone

persistence:
  enabled: true
  storageClass: longhorn
  size: 10Gi

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi
