---
portal_http_port: 80
portal_https_port: 443

portal_owner: "{{ nginx_owner }}"
portal_group: "{{ nginx_group }}"
portal_dir_mode: "{{ nginx_dir_mode }}"

portal_content_owner: "{{ nginx_content_owner }}"
portal_content_group: "{{ nginx_content_group }}"
portal_content_dir_mode: "{{ nginx_content_dir_mode }}"

portal_nginx_vhost: /etc/nginx/conf.d/portal.conf

portal_ssl_cert: /etc/pki/tls/certs/portal.crt
portal_ssl_key: /etc/pki/tls/private/portal.key
