FROM docker.io/rockylinux/rockylinux:10

RUN dnf install -y systemd sudo which python3 python3-dnf openssl procps-ng openssh-server cronie && \
    dnf clean all && \
    systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount

CMD ["/usr/sbin/init"]
