---
# Connection
ansible_host: 192.168.100.10

# VM host-specific
vm_name: ansible01
vm_mac: "52:54:00:aa:00:10"
vm_ip: 192.168.100.10

# DNS host-specific
vm_hostname: ansible01
vm_dns_entries:
  - name: harbor.local.lan
    ip: 192.168.100.10
