---
# Timezone
timezone: Europe/Amsterdam

# Packages
packages:
  - device-mapper-persistent-data
  - lvm2
  - curl
  - wget
  - git
  - vim

# Hosts entries
hosts_entries:
  - "192.168.100.10 harbor.local.lan"

# Harbor
harbor_version: "v2.11.0"
harbor_hostname: harbor.local.lan
harbor_tls_enabled: true
harbor_enable_trivy: false

# Firewall
firewall_ports:
  - 80/tcp
  - 443/tcp
  - 22/tcp
