apiVersion: v1
kind: Secret
metadata:
    name: gitlab-redis
    namespace: gitlab
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:TLs/nGVCyD68hc8b/dEA0gDtaLR4gJ9GsbXsr7jQda0=,iv:8GCtBzawTMgIswWWkwLlv8LlfNRpVB1SF7YdnuXxpnU=,tag:ENbzNDCtvylVq1W3vYJ8OQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRVhpNk1mczJlQmFxSUwy
            c0kxWHh6SjdTZnd1VjBHWDJXdS9uSmM3VFcwCnVxUlAzMUl0S3FLQVphRVhZOWpV
            eHZDMGJTUGtlb2JMS1lZekpONEtEUm8KLS0tIDJzYUVFbnNDdTNpVFlSTkNEUzB0
            VzdVNWc5MWNNOXg0ZHRCaWxTMnh6VE0Km+7ipoVx7isthGsY82zCjCxHEf1S1/d2
            xnyhvb9jkEOJ1OGrt0JAeJYmSCy0vJMGDU1IqrJP0P53Z0c1hUZetQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vhsg9zcjsyhzqxvaj9rmkwva27ur0s3ymunxfxx2e2vlr2m26aps3vfa98
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T09:53:46Z"
    mac: ENC[AES256_GCM,data:qlptA7bGIp+mvAazn0fvqmvQp8tFFqfUFnwSbeZfeM1Qp32qnYq0CKp2ql7nDDmHg/ez0PTa9QPTbp7XlpUONfY5bf0/tmvO7HsVtaqaw/odjgtL8XVmwgABHR3re4cbgd21RmqdLEWAfjC8oRg8vcQUUJ98DYYbtNJlsUC/UhM=,iv:qowRoJd72lX6Gw3KN5lCCPtl71xeU+dI1ooCxLkYM2o=,tag:GqFmpnK0Paf/BpyeqEJQ6A==,type:str]
    version: 3.13.3
