apiVersion: v1
kind: Secret
metadata:
    name: gitlab-initial-root-password
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:VggXwysO2KcwxSbxchtQdgbrC0xYNErG,iv:AjzuuGQplYNlnVICmLgoCVbHBj6h20bLOmuSkLclhDI=,tag:IJsLwyC9Qa5Oryut40CVoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRFo5WEhndnl1VDBVbEZh
            VTI4MW5KZEFiTk5FVGVGcUtRSW5GS2xXRjNjClNwbTJDdUJLRzNxVlpPRVlHRlBW
            a1RpWk5NYW91UlAxbXZCZWprN3hHTUEKLS0tIERNZHZNaGh5d0V4cnRkbzZOSngw
            MHpoU0trOUZoZUtXaU84ckNTbFp6S28KUdcnQ+1Wk+7VZsk9w9v0PzXAWjXdS+13
            cJJ/gZ6p+NosmIPtw7pH+mJfoHXLYkuQMgRCwQyGCycPoNgZPSLHrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vhsg9zcjsyhzqxvaj9rmkwva27ur0s3ymunxfxx2e2vlr2m26aps3vfa98
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T09:53:46Z"
    mac: ENC[AES256_GCM,data:6dwdet7UxeNeyuyP8potNVJbH/ipas53TDmKnRrsJNM3yV/eMNr+0cd9GCpsbDSTNe7V/yrxMEwLfGVA4Bi+Ez3VLYJC4PkCmNwBQ8ySP9aRBXCJNN/8nlKhuQUPCHWQ9wj3SwqJ3QKVlenEbMJEkl1bKCL3a7aLbIrXRkNUWI0=,iv:mAErTCmSaii4xzYdUJ5mgGnuWt1g7G32EjM8Ip8sjQ0=,tag:vZg1wQ/Kcvf6w8a3WsBpQA==,type:str]
    version: 3.13.3
