apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:XC0TdudZfjTVHJvnPcsILh+h7lQEasa2r9TBqjPxTKFawVz8uEAuzl1/yhmX8ulaAfee7/fiWHe+yflHTL8LtyTJyWWg4dCRPpw0MJZ0KCdyS3TQq76NwXmvfhhEQ5segKLuaKG8rkuli6a7mR/jlV9rjrwgLSJK1Ql07P8b+0Ad+RF0SgW69PnFvSGoXa/9TEI8RTq4DlS/TLyiIfkCsi9FuALrE20f5Z8nfjVh0//hPW5e4HTkg7QmYlLqg9f79Cc7GaaNwmIRYk5vupihM2mGOmunG9nurpqXK8nozzPMMfe/PFUqSFtG/jD8RbF/JXdJqSrnKjoFPS2D,iv:7kyyD4TMn9PSHWnUDE0HO0vHCQvqHqH9jxjkDOL+iVk=,tag:SjVmA+gYXWMb5lf6zMfk8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMWE5REgrWDg4N2dIOWhm
            QW5LVTdNcXppMGxuTnlubEQ3dm9DQkY3eDFzCmI0amxFN24xcWJuVnBVTTUza3Ns
            Qi9kZDRpTjdyR1VycStKOExjYXNDMGsKLS0tIDJ2QUtUM0Nkb3FMbEM2N25LSm8v
            aXFZYXMxT2hjMHdUekwrY1d4M2pabmcKpumT1nIAHXt/gYvuWGJjJENjOdJ1oR08
            4bnCIMuxiMsnd3YlzRmZ4dV1nXt6QUkz2jXcwmeMZFFa6/qYkF4g7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vhsg9zcjsyhzqxvaj9rmkwva27ur0s3ymunxfxx2e2vlr2m26aps3vfa98
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T09:53:46Z"
    mac: ENC[AES256_GCM,data:ji4V9/URHoGXbBFO1cPlqdxKqbYgRKhJB3W6i+kHXcJjoI+q9+UPlw3ECccoTC0c/VOR9IQyxUV2GfOHt29aKk0ZQOBlT9coyLa5j+sts0eFyGVhFqEtueHURpTFRWJ2cyIWHjI8psF9H2xjCs60I8XVbQE4YR8jm6cUSKsSXNc=,iv:pUiPzGTN6fnosNQYLz4b+LUTd90TYpViRPnSP0+n348=,tag:r1n8HG8WzLcnxuvnooJnMw==,type:str]
    version: 3.13.3
