apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-store
    namespace: gitlab
type: Opaque
stringData:
    connection: ENC[AES256_GCM,data:fxxtDDV3vSh9hD/K9+xsM7GRwZ6Drx38n1aWHXW/7O7x192Op1RutFlx/rV2640+SBzFQsLqUuh1A0Ve6B/fKPotI8wSVdSGG4Yht60cWnaq1hwGCmc9ymHs1ZwVXfKDnv1S6beqiHQeCHOo3aQRejq55N4K/7d7Z782FdBv82tANbh9efrSRMUkxcEI+xGD2POZq4t5IohD3+Ypk6BwzEFmZ2D5MbGsqmMTAwR2TCPx2VkCwZ2+Hc2WczXW2f5kdcU=,iv:yFrzvIHNearPM+LwsFDbolADEwVO4oeHZL0LMKZi384=,tag:RuYp5LbAtTpjJKRC+WfW1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQWtwc2JMVHZHY251OFJM
            TTNZYnJNRi9yZE5tbnU4Y0dVWEZ1Y1lhSGpJCkRBYjVLUWQ3VWQwN2wxaXdWNlFa
            N1hQZDNPVzNXVkV5U2xxdTYwYk9GYUEKLS0tIEhvK0FSd1pneVJ3UmZ4b1VqT2Rp
            VWV2LzY2cjFGN0ZpWWtuOU1RZkZRWUEKWhlFbwwgBNbT9h3apw4be+vO4GdD6CpX
            62q5FGWcSjKdvoHZTHa3miRqAEAswmhf7/O3XBZboO96gMKniIYcjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vhsg9zcjsyhzqxvaj9rmkwva27ur0s3ymunxfxx2e2vlr2m26aps3vfa98
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T09:53:46Z"
    mac: ENC[AES256_GCM,data:xUUWhvTRLu25EL/VN389ldqLd9mMZS6+PrSOONhOrTMmNBwE5h96uLg+4JBA/Mx4FnsThhAIZOAYMA3T1Jl8MdEVRFwVR7LtLIQJwgyLFskL+d9un36MBftPCAtOJc4JvcixHGDAf14E5ML5SUQGvWAcimzoS00RKuArjsE3OSo=,iv:tUuj/QpivVtXBPQDDSp5+N0S21EW2plnQc+HW4Qn3w0=,tag:0LF2pgTwg14q9FgGrp5o+g==,type:str]
    version: 3.13.3
