apiVersion: v1
kind: Secret
metadata:
    name: gitlab-postgresql
    namespace: gitlab
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:LOv8L5xX0mOZOxzEN+Q2yygs2FEzuU5rCBTDjBrkaeE=,iv:syzzufiS9x2jlt1ZnarGc6FPdPcY6UCevksjb9epYsM=,tag:+XaeuDhM2ONrtLTMpw92WQ==,type:str]
    password: ENC[AES256_GCM,data:hzhdOYi5Bl29hpmqomT0qluu/7SmZH8tSQL5ywpgfhQ=,iv:M0rZdcUZhn2Nj++oEzihIA0P2tm98yHixnL6DF+YRxE=,tag:nNicdr39l//9ME7qleTK2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArY0s2a056emczRW5TRTlo
            elJFbDdqd0piMU9WekFrb0hQTS9IeTRUSDNjCjlkSmUxR1dJOHM5NDRONE80cllB
            MDFrT08zalZnSjlKMkFVSDYrRWJwSU0KLS0tIE5QZTZFYmlkd2FFVFJTbTZRWkhP
            TkFRdS9OTDJZalNmUTY0em5IYnN0UzgKEOCwc2gAoLeNz5tKz1Hg/IupF6AXAnnf
            cddQODTYh+Rf6/NIthhX7SrAhtHYAmSEzck80yLqUehXOHVle1Ma9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vhsg9zcjsyhzqxvaj9rmkwva27ur0s3ymunxfxx2e2vlr2m26aps3vfa98
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T10:02:54Z"
    mac: ENC[AES256_GCM,data:yHUE89N/y85y7eq4wa9igde05iPO/xKYKwi/fw8aHejPI13VipdqV3XmOFnHgO3MyEKV6G0wl/pndhE48276TtxS0+fa+2cZIZ4Uy5HC+kwVA2hY9sbssJLBY+GVkbp6ePf9LU9kqY8v/EI3Blh5s+s4OfFh85Hm8e/7Z/sR1YU=,iv:T/ltOxEgwGLCl+cWumoAljEpvx9UB8y9zlkpoR/iSsQ=,tag:Y2W0YwpNQmPBAZnfxz50UQ==,type:str]
    version: 3.13.3
