apiVersion: v1
kind: Secret
metadata:
    name: gitlab-minio
    namespace: gitlab
type: Opaque
stringData:
    root-user: ENC[AES256_GCM,data:9HoCGb5lpkBt5ULrJGr3Y7D1IkOkAq82,iv:ogzyaGTAjcvvGxmJoJT3DWgYGyDFyNu1ZDJnFmb9kLk=,tag:/zz/B+IL0HfYM6mx3iYmVw==,type:str]
    root-password: ENC[AES256_GCM,data:UQGxF3SkZwF0x38OXOZ2trz6t0hF2Lz4,iv:vX316UAEQehNf7FP4L+DAOnHfmPk5FLY4ZTqQ4L/XAg=,tag:lYQG5+FaM7XHM3pi/NnD8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWnprVHN3TEg5dUxzc2cw
            QVR1NHlxZjNwcG0yZm5Ca3pLOU9KWmw2NFVZCm5LdTZ5bGx0L0hSaEZ2aW5LSS9v
            ZUtOcUtJSi9oUlFwV3ViVWVWMmgySDQKLS0tIExTb1JORDRHdUZZc1hNcnZWa1Nk
            NVhjVkZaRmhZZHdINEdmL1R1RXhiTGMKpeTGwzwNutOrxPcRVKsY4IUoq05FDt+y
            Ir5DozjrvPGGozEkfgj3Yj6EOtjMnHN4L0QP0tKqHIER+ek96PUjAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vhsg9zcjsyhzqxvaj9rmkwva27ur0s3ymunxfxx2e2vlr2m26aps3vfa98
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T09:53:46Z"
    mac: ENC[AES256_GCM,data:dnVSuMnhgRQThGT0fqh6Z5KdyFc89rUdWNvLxObMY/eI2bo8MPJR/Xw5YNoqp3pvW2nOzpdcE1zUpUgfrSpWKXUX+/DvQ6nlyRzeIzg8c83/eyIEO3JJrgSVWswkrKlseD5bE/3QLYP7Qjny7n7LVP0d6itCejDxU3YrVaxVrSY=,iv:tMSWRCl7FARkazsQTeB9iT0r8TD9B7Y2Xt59HMvvtd0=,tag:5ZWqM/IYSTyZ8Gpu5jURsg==,type:str]
    version: 3.13.3
