apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: gitlab-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - gitlab-postgresql.sops.yaml
  - gitlab-redis.sops.yaml
  - gitlab-minio.sops.yaml
  - gitlab-initial-root-password.sops.yaml
  - gitlab-object-store.sops.yaml
  - gitlab-registry-storage.sops.yaml
