---
packages_repo_dir: "{{ nginx_web_root }}/packages"
packages_repo_owner: "{{ nginx_content_owner }}"
packages_repo_group: "{{ nginx_content_group }}"
packages_repo_mode: "{{ nginx_content_dir_mode }}"
