---
packages_repo_dir: "{{ portal_packages_dir }}"
packages_repo_owner: "{{ portal_content_owner }}"
packages_repo_group: "{{ portal_content_group }}"
packages_repo_mode: "{{ portal_content_dir_mode }}"
