---
- name: Install firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Ensure firewalld is running
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Open required ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ firewall_ports }}"

- name: Allow required services
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ firewall_services }}"

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
