---
galaxy_info:
  role_name: kibana
  description: Kibana + nginx reverse proxy deployment
  author: alaureijs
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: EL
      versions:
        - "10"

dependencies: []
