apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: observability-kibana
  namespace: observability
  annotations:
    cert-manager.io/cluster-issuer: step-ca
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - observability.homelab.internal
      secretName: observability-tls
  rules:
    - host: observability.homelab.internal
      http:
        paths:
          - path: /kibana
            pathType: Prefix
            backend:
              service:
                name: observability-kb-http
                port:
                  number: 5601
