---
# Connection
ansible_host: 192.168.100.17

# VM host-specific
vm_name: ansible07
vm_mac: "52:54:00:aa:00:17"
vm_ip: 192.168.100.17

vm_hostname: ansible07
vm_vcpus: 2
vm_memory: 10240
vm_disk: 120

# Hardening — k8s networking requires IP forwarding
hardening_ip_forwarding: true
hardening_br_netfilter: true
