apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:xRNWWkc=,iv:ZKnJsx0h9llwLwYwbnSkBoGRkhFtUOm14+r8Gm5YfVU=,tag:rkQQCA0Fl/7iTNglh9puDg==,type:str]
    admin-password: ENC[AES256_GCM,data:ga99IlpMQeT/LLli68t6N/wYw1TxoFnQ,iv:byszi7yhGewwXUU/vvDVLbye8YI/Gvujw9iAxBi8tn8=,tag:lDV6mHU8k5n1Hur3b1NOsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOHY5bjYxRWpYUmRERDJv
            dDl5UTBCWXpmS3g0TUtpdnZtZTByUlJUd1IwCnVudW9IK3ZCNityZHNGUVFpMUlF
            SVcyLzVONldOaWU0MWZBOTAyQU9oNVEKLS0tIHJNU3RST3Y5bytVcW8xTWttdlFB
            anVWaEh0cy9Yd2svMDJFTUVUL0pKUG8Ke0uzHsj37gq92M499uAj21bYh8iPkj8x
            +R7B0JjJaG9ZsYS87+/PksHBqSC1z9DYfJafRyFyyOUtduHpLM3CPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vhsg9zcjsyhzqxvaj9rmkwva27ur0s3ymunxfxx2e2vlr2m26aps3vfa98
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T00:00:08Z"
    mac: ENC[AES256_GCM,data:jd5mcGb15Nc2k8HjnWqN/FpC3J456pd3Ik1nNWQg5FEkgH65Metjd7PPE3/+jMZpjMRsp7pL5mxRUkSkzF7fdCUcwksNjJ5H0R9IYElPRUf4IhyQqR9H+xadn5sUngf4cBHIHOlUYhKrXKPpw4M4qZbJyqQLlc8K5vQTfPY4XmE=,iv:LVA0WvT1jtUz8JONrELBaojjeZJHsn9u53Px+0RF6Og=,tag:kpZiX+7a16hMRUsbl4MZXg==,type:str]
    version: 3.13.3
