apiVersion: v1
kind: Secret
metadata:
    name: argocd-sops-age-key
    namespace: argocd
type: Opaque
data:
    keys.txt: ENC[AES256_GCM,data:jT4z2qDU1c46FnbnIKOtqQJnqWO/aZaQSjDRXUPnPgQACa+TnqEuUVASqBEwpOC2UAf9feeP/GIczZOqWjzLSPiVhDS/mQlTA1ALBWCQwrAztpvytmPDgfW+V6iyhUgeiX7LKLwez7FdciM9YHaUJqqGp9bjGm/2ErpIv2xFW3uj7MdiC7R6dlsDKyGXITRKSZJrQE4WG/tBocpGqfj34t0vHQU7u9vEpywtWVdhYZb9k05Tcb3lULRJB0lBHZbjkDlgxR/XYAAxEg3tZbdN3sOZ10dyFLzny686nvrMK89RkZ9EUzmhaVNkEefP+psxMwaK1QppkaMJYKox,iv:nwj0a7WKKfg2kiKIKyDlWsrGyJfwKsItGcLsKyKUZGY=,tag:wfUNiaWsWA7tRwhRARBzpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVEdodFlwUW9sNjhudVlP
            dGRlZ3IxMjNzQVdxZ1JEcFFNWVZDR3ZWQ3drCnF4ay8zanRNT1FDUnhCbFRvOTho
            YmVSZUhxTndody91TU5vQ0k4aVlXSHMKLS0tIHJZUyszSHd3THFDdXBXeFR0a0Fm
            bEM2UGxJU2xPc25ZUTFqOWtGajVGcjAKms4gSKqxInsA7tHYbL0XRww9Rt1L6ceO
            pJSfRE0OQC5U+tfHUWptAkmaRnwJWVLQc0eQVeP5XQdDyT68oVuQUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vhsg9zcjsyhzqxvaj9rmkwva27ur0s3ymunxfxx2e2vlr2m26aps3vfa98
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T16:09:42Z"
    mac: ENC[AES256_GCM,data:78pCDmQmnkfuxGOkEv3M/ffX43aD+J7fc3D8nBUXj8QK672jbKoUt5JILeRUH8prZFRRyL8y/oXhuAfQVHTUXWWDcZFzul7dFnVnXjB4hQd1xe/VgY4exZRlMYi/DcxMbIAvkSLjRMfQMmS7WGGe2oaQd1KguOT+a0atYOGqnj4=,iv:34+lTgLddJYD+jI6bo8D5YnPo4AVL3Q8sDjDZhYBhpY=,tag:0Vcl464f6kvzlbWZplWXOw==,type:str]
    version: 3.13.3
