apiVersion: v1
kind: Secret
metadata:
    name: argocd-admin-password
    namespace: argocd
type: Opaque
data:
    password: ENC[AES256_GCM,data:1k1c4sIfqSV7UMlrNcK/jT9T0xLpFTWq23qCiyjXyes=,iv:oaQn4QC8NWtymG5Qu5Rkuq/qoyXVletG4v2PSpKQIvo=,tag:/I/tkFcmgrguSRYNaGa86A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dzBCOXFJL1NJTndBclIz
            Mk5xYk1oeUtBeEc4RWxDK0ljS084WDRCM0RVCkp0U0h3TkFkNnFRZlhYUEQrTkVZ
            aUtaZzlGOWFJM1lFOWNYN3hoWXJBRFkKLS0tIHZNZHF0MkFxNkJqU0FxOEhPKy9D
            N1JhVWE4NjYyWkNvZmpxd0NPK1lONGcKpplI1BZUnpLNo23x9GrmHJj3o2PxzATU
            4Urgsec/oNb4hRYwMG0yBRrZWN/3dsb5/HVHAgncI/7pOy41Dwnb9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vhsg9zcjsyhzqxvaj9rmkwva27ur0s3ymunxfxx2e2vlr2m26aps3vfa98
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T16:09:42Z"
    mac: ENC[AES256_GCM,data:HtbRGsuC1Nw3L/AfZKQPukAjCzyU1YHF4NNnRUNpzIGUbbZ1uO1MGy5i/fgbqRdTNynI5fYxXOtCG6SxhdnlkkNzLG1GB5MEW3/6LSMWsIXuR9E/hQtY8zsHeP1gaOOBIAi3nsPYlgM/a7+ReN8ZEbnJAwq0GRq6Q/umGJOMHKQ=,iv:8touCssWqRf+jKyW9tww+aTHIPyjM3TQrQ/KeVJLqr4=,tag:UhAECoyc8iVyWNA0z5C61g==,type:str]
    version: 3.13.3
