apiVersion: v1
kind: Secret
metadata:
    name: argocd-repo-ssh-key
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: ENC[AES256_GCM,data:PnUM,iv:dBNeZtOwXv/N4Z9b/CwMSIntLVVQgc4xpE/i+55mTGw=,tag:R1vTqTDG27RVGChzIL2J3Q==,type:str]
    url: ENC[AES256_GCM,data:0RFNNHdk2za2N+mmVR0oz3B92eX26euoxK4YTaZQlMheLbLM,iv:XcbtT5rTeEByswD8pMtlgbFvWtslGD3qzi1RncMHf1Y=,tag:6Jvn2Zo2uagLrdGaBAyY1g==,type:str]
data:
    sshPrivateKey: ENC[AES256_GCM,data:ndY5bBPV2FPZ11Vt5Ou4ULkaAiX44ERGMHlRiBxd8uqB9k7AsjNb+RB25qcgiLajmvCCCB/wa52a4PCGmRFY62kHJy3RZizZBdf0zVGhXsjZ1tRPJjU2xjRrt1HvbEw/yU1HUsM9R0UfxQ/cu/DYkUP38w1nxkTdLH7Z0VHqmuKhFfyXVvVooxLoXF5tQEsgA3/WhqLdkv+EYrpSqkHhX+pw5i5MUVFWfyGSehCHabQAAZpxjOT1Rtu+5IohxDT/6L6aXTQvO8UbhRnL9CA7wYzX0nxrg3wk19CB5gLzd4y8ojnYz6xY4uazTnDblN3tkof7LbvcuKCVzod7v6jQSG87uR8paZHzoEC5NrxD/0B79hrDZhL1ULjY0f61LDDiDbDi1ULUgX1L7LxoJDIAJ+c5F3biBadHyowBiWATpv0B/zaSTsIoj1Jhd8rgdLNSwsEkA4pnozijsKw0prLS4e31mNVA5k2iRSr3kmpZ3T4rboY46+eJxZKsL4A2os6f5jy2Ofz6v6zyuUCH8rqenPWxMcIiPX1nGbtWv6FzlKBqIi7B5HML+YFuSgXSUI6m+shvCs5g1vp/HHOL21sxhXqRMAZRsQgFm1AC5SXkAxbj0+MuAckXOzuE/wuFm9Dc9EZejVX+2nHNNDXnNlONE6ED6N0ln78B94zDX7XjCvCtz1+hEYt3q6C43eMbyrOygccfRlcf/NaYqc3oLPT3BUi1DJy1FAjdKixSmgZf+SE=,iv:L2AuQGyC0XtiNcsNZx7pq1Q7+GdNozymu88ZSJTnjV8=,tag:hvzrPhdxYy3dsJ843RMHzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWTFSTDJyYUpuamlNcitw
            LzdMV01ScklPZHd5T28yL1pNMVpRMlVRcmxVCkN4OWxLMHF5aTZXTUx5SDA4YUlQ
            c1RQblAxdWJDd2t4MjJ3SGVBaEdIVzgKLS0tIHRzdXorMTAxK0tZUkxmb0E4UDds
            cTc1MHpXMEsrc3MvOTE5SEJlV2RlWlUKsrRyt7IY20K/g48+S+qJjKKsBkDjmMig
            6A7SWXkBKywMXwUeIYclGm6DMqGVM+qsL/5skX72VfpunEy/j1fGNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vhsg9zcjsyhzqxvaj9rmkwva27ur0s3ymunxfxx2e2vlr2m26aps3vfa98
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T16:09:42Z"
    mac: ENC[AES256_GCM,data:FKoGnopDmT3Z+IH0Kusbcdgwo/t2r/0I0oSW+cFqub8qAbiRCUC7SSOnkWtkSXxPwp7NeIQD3aHEUOpeb9gieVaGuAm+CX4IWaApc+7YtJdx9R4DadycMdj6ZLPsxKIzCT0MOXmI95NNDzfA1p7OlX0gwyD1R3d8iGbwkSJt1a8=,iv:14mJ4T3dD1MmlrFCGmh4NouZJRATIq7KX+yHHVLOwis=,tag:DCn61DUSc1MWOzZeAt48SA==,type:str]
    version: 3.13.3
