---
# Connection
ansible_host: 192.168.100.12

# VM host-specific
vm_name: ansible03
vm_mac: "52:54:00:aa:00:12"
vm_ip: 192.168.100.12

# VM specs (overrides group defaults)
vm_vcpus: 2
vm_memory: 8192
vm_disk: 120

vm_hostname: ansible03

# Hardening — Podman requires IP forwarding
hardening_ip_forwarding: true

# OpenTelemetry filelog paths
otel_log_paths:
  - /var/log/nginx/*.log
  - /var/log/elk/*.log
