apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: loki
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: loki
      repoURL: https://grafana-community.github.io/helm-charts
      targetRevision: 17.4.11
      helm:
        valueFiles:
          - $values/cluster/base/loki/values.yaml
    - chart: promtail
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.17.0
      helm:
        valueFiles:
          - $values/cluster/base/loki/promtail-values.yaml
    - repoURL: git@github.com:alaureijs/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
