apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: gitlab
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: minio
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 17.0.21
      helm:
        valueFiles:
          - $values/cluster/base/minio/values.yaml
    - repoURL: git@github.com:alaureijs/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
