apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: observability
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: eck-operator
      repoURL: https://helm.elastic.co
      targetRevision: 3.4.1
    - chart: opentelemetry-operator
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.120.0
    - repoURL: git@github.com:alaureijs/homelab.git
      targetRevision: HEAD
      path: cluster/base/observability
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
