---
galaxy_info:
  role_name: podman
  author: alaureijs
  description: Install Podman, Buildah, Skopeo, and podman-compose
  license: GPL-3.0-or-later
  min_ansible_version: "2.17"
  platforms:
    - name: EL
      versions:
        - "10"
  galaxy_tags:
    - podman
    - containers
    - buildah
    - skopeo

dependencies: []
