---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Assert firewalld running
      ansible.builtin.assert:
        that:
          - "'firewalld.service' in ansible_facts.services"
          - ansible_facts.services['firewalld.service'].state == 'running'
        fail_msg: "firewalld not running"

    - name: List firewalld ports
      ansible.builtin.command: firewall-cmd --list-ports
      changed_when: false
      register: firewall_ports_result

    - name: Assert only minimum port open
      ansible.builtin.assert:
        that:
          - "'22/tcp' in firewall_ports_result.stdout"
          - "'80/tcp' not in firewall_ports_result.stdout"
          - "'443/tcp' not in firewall_ports_result.stdout"
        fail_msg: "Unexpected firewall ports. Got: {{ firewall_ports_result.stdout }}"
