---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    firewall_backend: firewalld
    firewall_ports:
      - 80/tcp
      - 443/tcp
    firewall_services:
      - ssh

  roles:
    - role: firewall
