---
- name: Set image project and short name facts
  ansible.builtin.set_fact:
    harbor_containers_project: "{{ item.0.name | regex_replace('([^/]+)/.*', '\\1') }}"
    harbor_containers_short: "{{ item.0.name | regex_replace('.*/', '') }}"

- name: Pull image through proxy cache
  containers.podman.podman_image:
    name: "{{ harbor_hostname }}/{{ harbor_config_proxy_projects[item.0.registry] }}/{{ item.0.name }}"
    tag: "{{ item.1 }}"
    pull: true
    force: true
    validate_certs: false
    auth_file: "{{ harbor_containers_auth_dir }}/auth.json"

- name: Tag image for Harbor project
  containers.podman.podman_tag:
    image: "{{ harbor_hostname }}/{{ harbor_config_proxy_projects[item.0.registry] }}/{{ item.0.name }}:{{ item.1 }}"
    target_names:
      - "{{ harbor_hostname }}/{{ harbor_containers_project }}/{{ harbor_containers_short }}:{{ item.1 }}"

- name: Push image to Harbor project
  ansible.builtin.shell: |
    podman push --tls-verify=false --authfile "{{ harbor_containers_auth_dir }}/auth.json" "{{ harbor_hostname }}/{{ harbor_containers_project }}/{{ harbor_containers_short }}:{{ item.1 }}"
  args:
    executable: /bin/bash
