apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca
spec:
  acme:
    server: https://pki.homelab.internal/acme/acme/directory
    email: admin@homelab.internal
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJtVENDQVQ2Z0F3SUJBZ0lSQU5kNkI0TjREUTlIV0NvVGxaRCs3elF3Q2dZSUtvWkl6ajBFQXdJd0tqRVAKTUEwR0ExVUVDaE1HVEdGaUlFTkJNUmN3RlFZRFZRUURFdzVNWVdJZ1EwRWdVbTl2ZENCRFFUQWVGdzB5TmpBNApNREl4TWpFeE1UWmFGdzB6TmpBM016QXhNakV4TVRaYU1Db3hEekFOQmdOVkJBb1RCa3hoWWlCRFFURVhNQlVHCkExVUVBeE1PVEdGaUlFTkJJRkp2YjNRZ1EwRXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVFEKM2oxaHlRWElGMzNOMHdSaG1QTTRFZ1lRUVBSNkEvY0syalBLRjVQR2swRTE0Q0p5MWo4NFhGNUZaVTNuWk0xcApqWHIwcDVUTkJCNU9HYTFsbHY0U28wVXdRekFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lEVlIwVEFRSC9CQWd3CkJnRUIvd0lCQVRBZEJnTlZIUTRFRmdRVTkrM1haK0pVNEE2WFU5U2x0NmNUTmhieHlNb3dDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUxUM095bE9WU2llemJhc0sxY1VMNHFBb2tlMDk0OWwyTkVtTG1CRVd4VmhBaUVBOW1HRgpRVVljbGlBc0lPczhXOHdXMmxuYWJpT2x3Ri9GNVQ3aml0ZmVVL0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    privateKeySecretRef:
      name: step-ca-acme-key
    solvers:
      - http01:
          ingress:
            ingressClassName: cilium
