global:
  storageClass: longhorn

architecture: standalone

auth:
  username: gitlab
  database: gitlabhq_production
  existingSecret: gitlab-postgresql

primary:
  persistence:
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  extendedConfiguration: |
    max_locks_per_transaction = 640

metrics:
  enabled: false
