---
# Harbor configuration

harbor_version: "v2.11.0"
harbor_hostname: harbor.local.lan
harbor_tls_enabled: true
harbor_enable_trivy: false
harbor_enable_chartmuseum: false

# Paths
harbor_install_dir: /opt/harbor
harbor_data_dir: /data/harbor
harbor_tls_cert_path: "/etc/pki/tls/certs/harbor.crt"
harbor_tls_key_path: "/etc/pki/tls/private/harbor.key"

# Ports
harbor_http_port: 80
harbor_https_port: 443
harbor_internal_port: 4443

# Passwords
harbor_admin_password: "Harbor12345"
harbor_database_password: "Harbor12345"
harbor_redis_password: "Harbor12345"

# Storage
harbor_storage_filesystem_rootdirectory: /data/harbor/storage

# Firewall
firewall_ports:
  - 80/tcp
  - 443/tcp
  - 22/tcp

# Hosts entries
hosts_entries:
  - "192.168.100.10 harbor.local.lan"
