---
galaxy_info:
  role_name: ca-portal
  author: alaureijs
  description: nginx webserver for CA certificate distribution and ACME proxy
  license: GPL-3.0-or-later
  min_ansible_version: "2.17"
  platforms:
    - name: Rocky
      versions:
        - "10"
  galaxy_tags:
    - nginx
    - pki
    - certificates

dependencies:
  - role: step-ca
  - role: certificates
