---
- name: Ensure mTLS CA exists
  ansible.builtin.import_playbook: ensure-mtls-ca.yml

- name: Regenerate Harbor TLS certificates
  hosts: ansible01
  become: true
  gather_facts: true

  pre_tasks:
    - name: Merge certificates lists
      ansible.builtin.set_fact:
        certificates: "{{ certificates + certificates_extra | default([]) }}"

  roles:
    - role: certificates
    - role: harbor
