---
# Play 0: Common roles on all hosts
- name: Common roles on all hosts
  ansible.builtin.import_playbook: provision-common.yml

# Play 1: Deploy Elasticsearch
- name: Deploy Elasticsearch
  hosts: elk
  become: true
  gather_facts: true

  roles:
    - role: elasticsearch

# Play 3: Deploy Logstash
- name: Deploy Logstash
  hosts: elk
  become: true
  gather_facts: true

  roles:
    - role: logstash

# Play 4: Deploy Kibana
- name: Deploy Kibana
  hosts: elk
  become: true
  gather_facts: true

  roles:
    - role: kibana
