---
- name: Apply common configuration to all hosts
  hosts: all
  gather_facts: true
  roles:
    - common

- name: Configure webservers
  hosts: webservers
  gather_facts: true
  roles:
    - nginx

- name: Configure databases
  hosts: dbservers
  gather_facts: true
  roles:
    - postgres
