---
# podman role defaults

podman_packages:
  - podman
  - buildah
  - skopeo

podman_pip_packages:
  - podman-compose

podman_enable_socket: true
podman_registries:
  - docker.io
  - quay.io
  - ghcr.io
