---
# Logstash role defaults

logstash_image: "{{ harbor_hostname }}/library/logstash:{{ logstash_version }}"
logstash_heap_size: "2g"
logstash_http_port: 9600
logstash_beats_port: 5044
logstash_config_template: "{{ role_path }}/templates/logstash.yml.j2"
logstash_pipeline_template: "{{ role_path }}/templates/pipeline.conf.j2"
