loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: 2026-08-15
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: longhorn
    size: 20Gi

chunksCache:
  enabled: false

memcached:
  enabled: false

lokiCanary:
  enabled: false

test:
  enabled: false
